"""create initial tables

Revision ID: 75bc658819fe
Revises: 
Create Date: 2026-05-26 14:25:39.406459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75bc658819fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_table('datas_bloqueadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=False),
    sa.Column('bloqueado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datas_bloqueadas_data'), 'datas_bloqueadas', ['data'], unique=True)
    op.create_index(op.f('ix_datas_bloqueadas_id'), 'datas_bloqueadas', ['id'], unique=False)
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_pedido', sa.String(length=20), nullable=False),
    sa.Column('nome_cliente', sa.String(length=150), nullable=False),
    sa.Column('paroquia', sa.String(length=150), nullable=False),
    sa.Column('data_retirada', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('AGUARDANDO_PAGAMENTO', 'CONFIRMADO', 'ENTREGUE', name='statuspedido'), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=20), nullable=False),
    sa.Column('pix_payload', sa.String(length=500), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('regiao_administrativa', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.create_index(op.f('ix_pedidos_numero_pedido'), 'pedidos', ['numero_pedido'], unique=True)
    op.create_table('itens_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('sabor', sa.String(length=100), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('meio_a_meio_sabores', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_pedido_id'), 'itens_pedido', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itens_pedido_id'), table_name='itens_pedido')
    op.drop_table('itens_pedido')
    op.drop_index(op.f('ix_pedidos_numero_pedido'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_datas_bloqueadas_id'), table_name='datas_bloqueadas')
    op.drop_index(op.f('ix_datas_bloqueadas_data'), table_name='datas_bloqueadas')
    op.drop_table('datas_bloqueadas')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
