export const REGIOES_DF = [
  "Águas Claras",
  "Arapoanga",
  "Brazlândia",
  "Candangolândia",
  "Ceilândia",
  "Cruzeiro",
  "Fercal",
  "Gama",
  "Guará",
  "Itapoã",
  "Jardim Botânico",
  "Lago Norte",
  "Lago Sul",
  "Núcleo Bandeirante",
  "Paranoá",
  "Park Way",
  "Planaltina",
  "Plano Piloto",
  "Recanto das Emas",
  "Riacho Fundo I",
  "Riacho Fundo II",
  "Samambaia",
  "Santa Maria",
  "São Sebastião",
  "SCIA / Estrutural",
  "SIA",
  "Sobradinho",
  "Sobradinho II",
  "Sol Nascente / Pôr do Sol",
  "Taguatinga",
  "Varjão",
  "Vicente Pires",
  "Arniqueiras",
];
